# Generated by Django 5.0.6 on 2026-05-29 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_no", models.CharField(max_length=20, unique=True)),
                ("items", models.JSONField(default=list)),
                ("promotions", models.JSONField(default=list)),
                ("gifts", models.JSONField(default=list)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("final_amount", models.DecimalField(decimal_places=0, max_digits=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Tiền mặt"),
                            ("transfer", "Chuyển khoản"),
                            ("combined", "Kết hợp"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "transfer_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Chưa nhận"),
                            ("received", "Đã nhận"),
                            ("partial", "Nhận một phần"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending_kt", "Chờ KT duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hợp đồng",
                "ordering": ["-created_at"],
            },
        ),
    ]
