# Generated by Django 6.0.5 on 2026-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sale_round',
            field=models.CharField(choices=[('sale', 'Sale (vòng 1)'), ('upsale', 'Upsale (vòng 2+)')], default='sale', max_length=10),
        ),
    ]
