# Generated by Django 6.0.5 on 2026-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_sale_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='so_buoi',
            field=models.PositiveIntegerField(default=0, help_text='Tong so buoi lieu trinh mua'),
        ),
    ]
