# Generated by Django 6.0.5 on 2026-07-21 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_hangcho_checkout'),
        ('contracts', '0003_contract_so_buoi'),
        ('customers', '0006_customer_services_interest'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_buoi', models.PositiveIntegerField(default=0, help_text='Tong so buoi mua cho dich vu nay')),
                ('note', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='contracts.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_courses', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='services.service')),
            ],
            options={
                'verbose_name': 'Lieu trinh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='appointments.appointment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contracts.treatmentcourse')),
                ('ktv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buoi dieu tri',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
