# Generated by Django 5.0.6 on 2026-05-29 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Nam"), ("F", "Nữ")], max_length=10
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("zalo", "Zalo"),
                            ("google", "Google/Maps"),
                            ("instagram", "Instagram"),
                            ("gioi_thieu", "Giới thiệu"),
                            ("walkin", "Walk-in"),
                            ("khac", "Không xác định"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("nong", "Nóng"), ("am", "Âm"), ("thuong", "Thường")],
                        default="thuong",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("chua_goi", "Chưa gọi"),
                            ("da_goi", "Đã gọi"),
                            ("khong_nghe", "Không nghe máy"),
                            ("thue_bao", "Thuê bao"),
                            ("sai_so", "Sai số"),
                            ("tu_choi", "Từ chối"),
                            ("hoan_so", "Hoàn số"),
                            ("dat_lich", "Đặt lịch"),
                            ("hen_goi", "Hẹn gọi lại"),
                            ("can_tv", "Cần tư vấn thêm"),
                            ("khong_qt", "Không quan tâm"),
                        ],
                        default="chua_goi",
                        max_length=20,
                    ),
                ),
                ("call_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "SALE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tele",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "TELE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tele_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Khách hàng",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_number", models.IntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("chua_goi", "Chưa gọi"),
                            ("da_goi", "Đã gọi"),
                            ("khong_nghe", "Không nghe máy"),
                            ("thue_bao", "Thuê bao"),
                            ("sai_so", "Sai số"),
                            ("tu_choi", "Từ chối"),
                            ("hoan_so", "Hoàn số"),
                            ("dat_lich", "Đặt lịch"),
                            ("hen_goi", "Hẹn gọi lại"),
                            ("can_tv", "Cần tư vấn thêm"),
                            ("khong_qt", "Không quan tâm"),
                        ],
                        max_length=20,
                    ),
                ),
                ("consult_result", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "recording_file",
                    models.FileField(blank=True, upload_to="recordings/"),
                ),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tele",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="call_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử gọi",
                "ordering": ["-called_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="customer_images/%Y/%m/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("truoc", "Trước ĐT"),
                            ("trong", "Trong ĐT"),
                            ("sau", "Sau ĐT"),
                            ("tinh_trang", "Tình trạng"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="customers.customer",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("recording_file", models.FileField(upload_to="recordings/")),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("treu", "KH trêu / số ảo"),
                            ("khong_ton_tai", "Số không tồn tại"),
                            ("nham_so", "Không nhớ để lại số"),
                            ("trung", "Số trùng KH cũ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="customers.customer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yêu cầu hoàn số",
                "ordering": ["-created_at"],
            },
        ),
    ]
