# Generated by Django 6.0.5 on 2026-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_cskh_new_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='result',
            field=models.CharField(choices=[('chua_goi', 'Chưa gọi'), ('da_goi', 'Đã gọi'), ('khong_nghe', 'Không nghe máy'), ('thue_bao', 'Thuê bao'), ('sai_so', 'Sai số'), ('tu_choi', 'Từ chối'), ('hoan_so', 'Hoàn số'), ('dat_lich', 'Đặt lịch'), ('hen_goi', 'Hẹn gọi lại'), ('can_tv', 'Cần tư vấn thêm'), ('khong_qt', 'Không quan tâm'), ('cho_phan_cskh', 'Chờ phân CSKH'), ('dang_cham_soc', 'Đang chăm sóc')], max_length=20),
        ),
    ]
