# Generated by Django 6.0.5 on 2026-06-23 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ads',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MKT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
