# Generated by Django 6.0.5 on 2026-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_ads'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='services_interest',
            field=models.ManyToManyField(blank=True, related_name='interested_customers', to='services.service'),
        ),
    ]
