# Generated by Django 6.0.5 on 2026-10-04 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_services_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('khai_thac', 'Khai thác'), ('cham_soc', 'Chăm sóc'), ('dieu_tri', 'Điều trị'), ('noi_bo', 'Nội bộ')], default='khai_thac', max_length=20)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Ghi chú khách hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
