# Generated by Django 6.0.5 on 2026-06-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Phòng khám'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('QUAN_LY', 'Quản lý'), ('CHU_DN', 'Chủ doanh nghiệp'), ('LEAD_SALE', 'Lead Sale'), ('LEAD_TELE', 'Lead Tele'), ('LEAD_CSKH', 'Lead CSKH'), ('SALE', 'Sale'), ('TELE', 'Tele'), ('CSKH', 'CSKH'), ('LE_TAN', 'Lễ tân'), ('KE_TOAN', 'Kế toán'), ('MKT', 'Marketing'), ('LEAD_MKT', 'Lead Marketing'), ('TRUC_PAGE', 'Trực page'), ('LEAD_TRUC_PAGE', 'Lead Trực page'), ('BS', 'Bác sĩ'), ('KTV', 'Kỹ thuật viên')], max_length=20),
        ),
    ]
