# Generated by Django 5.0.6 on 2026-05-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "clinic_type",
                    models.CharField(
                        choices=[("daLieu", "Da liễu"), ("nhaKhoa", "Nha khoa")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục DV",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=0, max_digits=15)),
                ("sessions", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dịch vụ",
            },
        ),
    ]
