# Generated by Django 5.0.6 on 2026-05-29 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaloConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oa_id", models.CharField(max_length=100, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zalo OA Config",
            },
        ),
        migrations.CreateModel(
            name="ZaloMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zalo_user_id", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("out", "Gửi đi"), ("in", "Nhận về")], max_length=4
                    ),
                ),
                (
                    "msg_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Nhắc lịch hẹn"),
                            ("tua_confirm", "Xác nhận tua"),
                            ("contract_info", "Thông tin HĐ"),
                            ("general", "Chung"),
                            ("webhook_in", "Webhook nhận"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("status", models.CharField(default="sent", max_length=20)),
                ("error", models.TextField(blank=True)),
                ("related_appointment_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZaloUserBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zalo_user_id", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zalo_binding",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zalo_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
