# Generated by Django 5.0.6 on 2026-05-29 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Tư vấn"),
                            ("treatment", "Điều trị"),
                            ("dental", "Nha khoa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="accounts.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng",
            },
        ),
    ]
