# Generated by Django 5.0.6 on 2026-05-29 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("calls_target", models.IntegerField(default=0)),
                ("calls_actual", models.IntegerField(default=0)),
                ("appointments_target", models.IntegerField(default=0)),
                ("appointments_actual", models.IntegerField(default=0)),
                (
                    "revenue_target",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                (
                    "revenue_actual",
                    models.DecimalField(decimal_places=0, default=0, max_digits=15),
                ),
                ("contracts_target", models.IntegerField(default=0)),
                ("contracts_actual", models.IntegerField(default=0)),
                (
                    "achievement_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "month", "year")},
            },
        ),
    ]
