# Generated by Django 6.0.5 on 2026-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_kpitarget_alter_kpirecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpirecord',
            name='achievement_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% hoàn thành KPI tổng hợp', max_digits=5),
        ),
        migrations.AlterField(
            model_name='kpirecord',
            name='tua_count',
            field=models.IntegerField(default=0, help_text='Số tua xác nhận trong tháng'),
        ),
    ]
