# Generated by Django 5.0.6 on 2026-05-29 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tua_rate",
                    models.DecimalField(decimal_places=0, default=0, max_digits=8),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình lương",
            },
        ),
        migrations.CreateModel(
            name="MonthlySalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("working_days", models.IntegerField()),
                ("base", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "commission",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "tua_income",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("approved", "Đã duyệt"),
                            ("paid", "Đã thanh toán"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_salaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lương tháng",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "month", "year")},
            },
        ),
    ]
