# Generated by Django 6.0.5 on 2026-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salaryconfig_fields_monthlysalary_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryconfig',
            options={'verbose_name': 'Cấu hình lương'},
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='actual_days',
            field=models.IntegerField(default=0, help_text='Ngày thực tế có mặt'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='absent_deduct_per_day',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Khấu trừ mỗi ngày vắng không phép (VNĐ)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% hoa hồng trên doanh thu HĐ', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='late_deduct_per_minute',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Khấu trừ mỗi phút đi muộn (VNĐ)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='tua_rate',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Tiền thưởng mỗi tua xác nhận (VNĐ)', max_digits=8),
        ),
    ]
