# Generated by Django 5.0.6 on 2026-05-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="shiftassignment",
            options={"ordering": ["date", "shift__start_time"]},
        ),
        migrations.AlterModelOptions(
            name="workshift",
            options={"ordering": ["start_time"], "verbose_name": "Ca làm việc"},
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="reject_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="source",
            field=models.CharField(
                choices=[("machine", "Máy chấm công"), ("manual", "Thủ công")],
                default="machine",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shiftassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="attendance.workshift",
            ),
        ),
        migrations.AlterField(
            model_name="workshift",
            name="name",
            field=models.CharField(
                choices=[
                    ("sang", "Sáng 08-12"),
                    ("chieu", "Chiều 12-17"),
                    ("toi", "Tối 17-20"),
                    ("full", "Full 08-17"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
