# Generated by Django 6.0.5 on 2026-06-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration_type',
            field=models.CharField(choices=[('full_day', 'Cả ngày'), ('half_morning', 'Nửa ngày sáng'), ('half_afternoon', 'Nửa ngày chiều'), ('hourly', 'Theo giờ')], default='full_day', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
