# Generated by Django 6.0.5 on 2026-10-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_bs_dieu_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment_course_ids',
            field=models.JSONField(blank=True, default=list, help_text='Cac goi lieu trinh lam trong buoi nay'),
        ),
    ]
