# Generated by Django 6.0.5 on 2026-06-17 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatchannel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
