# Generated by Django 6.0.5 on 2026-06-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatchannel_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Ảnh'), ('video', 'Video'), ('system', 'Hệ thống'), ('kh_share', 'Chia sẻ KH'), ('hd_share', 'Chia sẻ HĐ')], default='text', max_length=10),
        ),
    ]
